name: Our Josbs
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Hello'
          echo 'Yoonda Git Actions'
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run:  ls -al
